<a href="https://colab.research.google.com/github/JoaoVitorDeOliveira/machine-learning/blob/master/AnaliseDataSetWine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import files  #biblioteca utilizada para carregar os dados para o google colab
uploaded = files.upload()

Saving winequality-red.csv to winequality-red.csv


In [4]:
df = pd.read_csv('winequality-red.csv', sep=';')

In [5]:
df.shape

(1599, 12)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [7]:
df.describe()

fixed acidity  volatile acidity  ...      alcohol      quality
count    1599.000000       1599.000000  ...  1599.000000  1599.000000
mean        8.319637          0.527821  ...    10.422983     5.636023
std         1.741096          0.179060  ...     1.065668     0.807569
min         4.600000          0.120000  ...     8.400000     3.000000
25%         7.100000          0.390000  ...     9.500000     5.000000
50%         7.900000          0.520000  ...    10.200000     6.000000
75%         9.200000          0.640000  ...    11.100000     6.000000
max        15.900000          1.580000  ...    14.900000     8.000000

[8 rows x 12 columns]

In [25]:
df.head()

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5

[5 rows x 12 columns]

In [31]:
df.corr()

fixed acidity  volatile acidity  ...   alcohol   quality
fixed acidity              1.000000         -0.256131  ... -0.061668  0.124052
volatile acidity          -0.256131          1.000000  ... -0.202288 -0.390558
citric acid                0.671703         -0.552496  ...  0.109903  0.226373
residual sugar             0.114777          0.001918  ...  0.042075  0.013732
chlorides                  0.093705          0.061298  ... -0.221141 -0.128907
free sulfur dioxide       -0.153794         -0.010504  ... -0.069408 -0.050656
total sulfur dioxide      -0.113181          0.076470  ... -0.205654 -0.185100
density                    0.668047          0.022026  ... -0.496180 -0.174919
pH                        -0.682978          0.234937  ...  0.205633 -0.057731
sulphates                  0.183006         -0.260987  ...  0.093595  0.251397
alcohol                   -0.061668         -0.202288  ...  1.000000  0.476166
quality                    0.124052         -0.390558  ...  0.476166  1.000000

[12 rows x 12 columns]

In [44]:
df_menor = df[df['quality'] == 5]

In [45]:
df_menor.count()

fixed acidity           681
volatile acidity        681
citric acid             681
residual sugar          681
chlorides               681
free sulfur dioxide     681
total sulfur dioxide    681
density                 681
pH                      681
sulphates               681
alcohol                 681
quality                 681
dtype: int64

In [46]:
from sklearn.preprocessing import MinMaxScaler

In [127]:
scaler = MinMaxScaler()
entradas_normalizadas = scaler.fit_transform(df.drop(columns='quality', axis=1))
saida = df['quality']

In [103]:
print(entradas_normalizadas)

[[0.02560554]
 [0.00242215]
 [0.        ]
 ...
 [0.0117301 ]
 [0.00228374]
 [0.03806228]]


In [97]:
print(saida)

[[0.4]
 [0.4]
 [0.4]
 ...
 [0.6]
 [0.4]
 [0.6]]


In [61]:
from sklearn.model_selection import train_test_split

In [68]:
y = df['quality']
X = df.drop(columns='quality', axis=1)

In [128]:
x_train, x_test, y_train, y_test = train_test_split(entradas_normalizadas, saida, test_size=0.30, random_state=1)

In [105]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1)

In [124]:
x_train

array([[0.31858407, 0.82876712, 0.        , ..., 0.62204724, 0.09580838,
        0.38461538],
       [0.23893805, 0.25342466, 0.1       , ..., 0.44094488, 0.08383234,
        0.32307692],
       [0.36283186, 0.49315068, 0.        , ..., 0.41732283, 0.13173653,
        0.2       ],
       ...,
       [0.17699115, 0.41438356, 0.09      , ..., 0.48031496, 0.09580838,
        0.36923077],
       [0.2300885 , 0.34931507, 0.        , ..., 0.49606299, 0.1497006 ,
        0.09230769],
       [0.39823009, 0.19178082, 0.5       , ..., 0.37007874, 0.21556886,
        0.63076923]])

In [123]:
y_train

array([[0.4],
       [0.4],
       [0.4],
       ...,
       [0.6],
       [0.6],
       [1. ]])

In [129]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(1119, 11)
(1119,)
(480, 11)
(480,)


In [131]:
from sklearn.neighbors import KNeighborsClassifier
clf_KNN = KNeighborsClassifier(n_neighbors=5)
clf_KNN.fit(x_train, y_train)
pred = clf_KNN.predict(x_test)

In [132]:
from sklearn.metrics import accuracy_score
acuracia = accuracy_score(y_test, pred)
print('Acurácia do KNN: ',acuracia)

Acurácia do KNN:  0.5645833333333333


In [133]:
from sklearn.tree import DecisionTreeClassifier
clf_arvore = DecisionTreeClassifier()
clf_arvore.fit(x_train, y_train)
pred_tree = clf_arvore.predict(x_test)

In [134]:
acuracia_tree = accuracy_score(y_test, pred_tree)
print('Acurácia da àrvore de Decisão: ',acuracia_tree)

Acurácia da àrvore de Decisão:  0.5979166666666667


In [135]:
from sklearn.ensemble import RandomForestClassifier
clf_floresta = RandomForestClassifier(max_depth=10, random_state=1)
clf_floresta.fit(x_train, y_train)
pred_floresta = clf_floresta.predict(x_test)

In [136]:
acuracia_floresta = accuracy_score(y_test, pred_floresta)
print('Acurácia da floresta: ',acuracia_floresta)

Acurácia da floresta:  0.6791666666666667


In [137]:
from sklearn.svm import SVC
clf_svm=SVC(gamma='auto',kernel='rbf')
clf_svm.fit(x_train, y_train)
pred_svm = clf_svm.predict(x_test)

In [138]:
acuracia_svm = accuracy_score(y_test, pred_svm)
print('Acurácia da floresta: ',acuracia_svm)

Acurácia da floresta:  0.5854166666666667


In [143]:
from sklearn.neural_network import MLPClassifier
clf_mlp = MLPClassifier( alpha=1e-5, hidden_layer_sizes=(5, 5), random_state=1)
clf_mlp.fit(x_train, y_train)
pred_mlp = clf_mlp.predict(x_test)

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [144]:
acuracia_mlp = accuracy_score(y_test, pred_mlp)
print('Acurácia do MLP: ',acuracia_mlp)

Acurácia do MLP:  0.6


In [148]:
y_binario = (df['quality'] > 5).astype(int)

In [149]:
y_binario

0       0
1       0
2       0
3       1
4       0
       ..
1594    0
1595    1
1596    1
1597    0
1598    1
Name: quality, Length: 1599, dtype: int64

In [162]:
y_train_size = int(len(y_binario) * 0.70)
y_test_size = len(y_binario) - y_train
y_train, y_test = y_binario[0:y_train_size], y_binario[y_train_size:len(y_binario)]
print(len(y_train), len(y_test))

1119 480


In [163]:
clf_floresta = RandomForestClassifier(max_depth=10, random_state=1)
clf_floresta.fit(x_train, y_train)
pred_floresta = clf_floresta.predict(x_test)

In [164]:
acuracia_floresta = accuracy_score(y_test, pred_floresta)
print('Acurácia da floresta: ',acuracia_floresta)

Acurácia da floresta:  0.5104166666666666


In [159]:
x_train

array([[0.31858407, 0.82876712, 0.        , ..., 0.62204724, 0.09580838,
        0.38461538],
       [0.23893805, 0.25342466, 0.1       , ..., 0.44094488, 0.08383234,
        0.32307692],
       [0.36283186, 0.49315068, 0.        , ..., 0.41732283, 0.13173653,
        0.2       ],
       ...,
       [0.17699115, 0.41438356, 0.09      , ..., 0.48031496, 0.09580838,
        0.36923077],
       [0.2300885 , 0.34931507, 0.        , ..., 0.49606299, 0.1497006 ,
        0.09230769],
       [0.39823009, 0.19178082, 0.5       , ..., 0.37007874, 0.21556886,
        0.63076923]])